name: Push Features   
on:
  push:
    branches:
    - feature/**
  check_suite:
    types:
      - completed
  status: {}
  
  
jobs:
  # build and test
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    - run: flutter test
  merge-branch:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master

      - name: feature -> develop
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: develop
          github_token: ${{ github.token }}
